title: Documentation
author: Paul Radzkov
email: radzkov@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Documentation template
# twitter_username: paul_radzkov
github_username: paulradzkov
google_analytics: UA-29416794-1
